// lib/mockWisdomData.js
export const wisdomQuotes = [
  {
    id: 1,
    quote: "The mind is everything. What you think you become.",
    author: "Lord Buddha",
    category: "Wisdom",
    tags: ["Mind", "Thoughts", "Becoming"],
    source: "Dhammapada",
    color: "#FF7A00",
    bgGradient: "from-orange-50 to-amber-50 dark:from-orange-950/30 dark:to-amber-950/30",
    borderColor: "border-orange-200 dark:border-orange-800",
  },
  {
    id: 2,
    quote: "You are not a drop in the ocean. You are the entire ocean in a drop.",
    author: "Rumi",
    category: "Spiritual",
    tags: ["Ocean", "Self", "Unity"],
    source: "The Essential Rumi",
    color: "#4FC3F7",
    bgGradient: "from-blue-50 to-cyan-50 dark:from-blue-950/30 dark:to-cyan-950/30",
    borderColor: "border-blue-200 dark:border-blue-800",
  },
  {
    id: 3,
    quote: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Motivation",
    tags: ["Love", "Work", "Passion"],
    source: "Stanford Commencement Address",
    color: "#F4B400",
    bgGradient: "from-yellow-50 to-amber-50 dark:from-yellow-950/30 dark:to-amber-950/30",
    borderColor: "border-yellow-200 dark:border-yellow-800",
  },
  {
    id: 4,
    quote: "In the middle of difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Wisdom",
    tags: ["Difficulty", "Opportunity", "Growth"],
    source: "Various Writings",
    color: "#4CAF50",
    bgGradient: "from-green-50 to-emerald-50 dark:from-green-950/30 dark:to-emerald-950/30",
    borderColor: "border-green-200 dark:border-green-800",
  },
  {
    id: 5,
    quote: "The best time to plant a tree was 20 years ago. The second best time is now.",
    author: "Chinese Proverb",
    category: "Wisdom",
    tags: ["Action", "Time", "Growth"],
    source: "Ancient Proverb",
    color: "#8B5E3C",
    bgGradient: "from-amber-50 to-brown-50 dark:from-amber-950/30 dark:to-brown-950/30",
    borderColor: "border-amber-200 dark:border-amber-800",
  },
  {
    id: 6,
    quote: "Be the change that you wish to see in the world.",
    author: "Mahatma Gandhi",
    category: "Inspiration",
    tags: ["Change", "Action", "World"],
    source: "Various Writings",
    color: "#D32F2F",
    bgGradient: "from-red-50 to-rose-50 dark:from-red-950/30 dark:to-rose-950/30",
    borderColor: "border-red-200 dark:border-red-800",
  },
  {
    id: 7,
    quote: "What you seek is seeking you.",
    author: "Rumi",
    category: "Spiritual",
    tags: ["Seeking", "Connection", "Soul"],
    source: "The Essential Rumi",
    color: "#6A1B9A",
    bgGradient: "from-purple-50 to-violet-50 dark:from-purple-950/30 dark:to-violet-950/30",
    borderColor: "border-purple-200 dark:border-purple-800",
  },
  {
    id: 8,
    quote: "The journey of a thousand miles begins with one step.",
    author: "Lao Tzu",
    category: "Wisdom",
    tags: ["Journey", "Action", "Beginning"],
    source: "Tao Te Ching",
    color: "#FF5722",
    bgGradient: "from-orange-50 to-red-50 dark:from-orange-950/30 dark:to-red-950/30",
    borderColor: "border-orange-200 dark:border-orange-800",
  },
  {
    id: 9,
    quote: "Happiness is not something ready made. It comes from your own actions.",
    author: "Dalai Lama",
    category: "Happiness",
    tags: ["Happiness", "Action", "Self"],
    source: "The Art of Happiness",
    color: "#FFC107",
    bgGradient: "from-yellow-50 to-orange-50 dark:from-yellow-950/30 dark:to-orange-950/30",
    borderColor: "border-yellow-200 dark:border-yellow-800",
  },
  {
    id: 10,
    quote: "The mind is a powerful force. It can enslave us or empower us.",
    author: "Vivekananda",
    category: "Wisdom",
    tags: ["Mind", "Power", "Freedom"],
    source: "Complete Works of Vivekananda",
    color: "#2196F3",
    bgGradient: "from-blue-50 to-indigo-50 dark:from-blue-950/30 dark:to-indigo-950/30",
    borderColor: "border-blue-200 dark:border-blue-800",
  },
  {
    id: 11,
    quote: "Love is the bridge between you and everything.",
    author: "Rumi",
    category: "Love",
    tags: ["Love", "Connection", "Unity"],
    source: "The Essential Rumi",
    color: "#E91E63",
    bgGradient: "from-pink-50 to-rose-50 dark:from-pink-950/30 dark:to-rose-950/30",
    borderColor: "border-pink-200 dark:border-pink-800",
  },
  {
    id: 12,
    quote: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    author: "Lord Buddha",
    category: "Wisdom",
    tags: ["Present", "Mindfulness", "Meditation"],
    source: "Dhammapada",
    color: "#00BCD4",
    bgGradient: "from-cyan-50 to-teal-50 dark:from-cyan-950/30 dark:to-teal-950/30",
    borderColor: "border-cyan-200 dark:border-cyan-800",
  },
];

// Get today's quote (based on date)
export function getTodaysWisdom() {
  const today = new Date();
  const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
  const index = dayOfYear % wisdomQuotes.length;
  return wisdomQuotes[index];
}