// lib/mockAstroData.js
export const mockPanchang = {
  date: 'January 15, 2025',
  tithi: 'Ekadashi',
  tithiDetails: 'Krishna Paksha Ekadashi',
  nakshatra: 'Rohini',
  nakshatraDetails: 'Rohini Nakshatra until 02:34 PM',
  yoga: 'Vishkumbha',
  karana: 'Bava',
  sunrise: '06:30 AM',
  sunset: '06:45 PM',
  rahuKaal: '12:30 PM - 02:00 PM',
  abhijitMuhurat: '11:48 AM - 12:36 PM',
  amritKaal: '09:30 AM - 11:00 AM',
  specialEvent: 'Maha Shivaratri',
};

export const zodiacSigns = [
  { id: 'aries', symbol: '♈', name: 'Aries', nameHindi: 'मेष' },
  { id: 'taurus', symbol: '♉', name: 'Taurus', nameHindi: 'वृषभ' },
  { id: 'gemini', symbol: '♊', name: 'Gemini', nameHindi: 'मिथुन' },
  { id: 'cancer', symbol: '♋', name: 'Cancer', nameHindi: 'कर्क' },
  { id: 'leo', symbol: '♌', name: 'Leo', nameHindi: 'सिंह' },
  { id: 'virgo', symbol: '♍', name: 'Virgo', nameHindi: 'कन्या' },
  { id: 'libra', symbol: '♎', name: 'Libra', nameHindi: 'तुला' },
  { id: 'scorpio', symbol: '♏', name: 'Scorpio', nameHindi: 'वृश्चिक' },
  { id: 'sagittarius', symbol: '♐', name: 'Sagittarius', nameHindi: 'धनु' },
  { id: 'capricorn', symbol: '♑', name: 'Capricorn', nameHindi: 'मकर' },
  { id: 'aquarius', symbol: '♒', name: 'Aquarius', nameHindi: 'कुंभ' },
  { id: 'pisces', symbol: '♓', name: 'Pisces', nameHindi: 'मीन' },
];

export const mockHoroscope = {
  aries: {
    prediction: "Today brings new opportunities for personal growth. Trust your intuition and take bold steps forward.",
    color: '#FF4444',
    luckyNumber: 9,
    mood: 'Energetic',
    compatibility: 'Leo, Sagittarius',
  },
  taurus: {
    prediction: "Focus on your financial goals today. A practical approach will yield long-term benefits.",
    color: '#4CAF50',
    luckyNumber: 6,
    mood: 'Stable',
    compatibility: 'Virgo, Capricorn',
  },
  gemini: {
    prediction: "Communication is key today. Express your thoughts clearly and listen with an open heart.",
    color: '#FFC107',
    luckyNumber: 5,
    mood: 'Curious',
    compatibility: 'Libra, Aquarius',
  },
  cancer: {
    prediction: "Nurture your relationships today. Family and loved ones need your care and attention.",
    color: '#FF6B6B',
    luckyNumber: 2,
    mood: 'Nurturing',
    compatibility: 'Scorpio, Pisces',
  },
  leo: {
    prediction: "Step into the spotlight with confidence. Your leadership skills will inspire others today.",
    color: '#FF9800',
    luckyNumber: 1,
    mood: 'Confident',
    compatibility: 'Aries, Sagittarius',
  },
  virgo: {
    prediction: "Pay attention to the details. Your analytical skills will solve a long-standing problem.",
    color: '#8BC34A',
    luckyNumber: 4,
    mood: 'Analytical',
    compatibility: 'Taurus, Capricorn',
  },
  libra: {
    prediction: "Balance is everything today. Seek harmony in all aspects of your life.",
    color: '#E91E63',
    luckyNumber: 7,
    mood: 'Harmonious',
    compatibility: 'Gemini, Aquarius',
  },
  scorpio: {
    prediction: "Your intensity and passion will help you achieve your goals. Stay focused and determined.",
    color: '#9C27B0',
    luckyNumber: 8,
    mood: 'Intense',
    compatibility: 'Cancer, Pisces',
  },
  sagittarius: {
    prediction: "Adventure calls! Explore new ideas and expand your horizons today.",
    color: '#FF5722',
    luckyNumber: 3,
    mood: 'Adventurous',
    compatibility: 'Aries, Leo',
  },
  capricorn: {
    prediction: "Your hard work is about to pay off. Stay patient and trust the process.",
    color: '#607D8B',
    luckyNumber: 10,
    mood: 'Determined',
    compatibility: 'Taurus, Virgo',
  },
  aquarius: {
    prediction: "Your innovative ideas will shine today. Don't be afraid to think outside the box.",
    color: '#2196F3',
    luckyNumber: 11,
    mood: 'Innovative',
    compatibility: 'Gemini, Libra',
  },
  pisces: {
    prediction: "Trust your intuition today. Your creative and spiritual energy is at its peak.",
    color: '#00BCD4',
    luckyNumber: 12,
    mood: 'Intuitive',
    compatibility: 'Cancer, Scorpio',
  },
};